# Generated by Django 6.1.1 on 2026-09-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_contactmessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='cover_image',
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='reason',
            field=models.CharField(choices=[('project', 'Project'), ('employment', 'Employment'), ('collaboration', 'Collaboration'), ('general', 'General inquiry')], default='general', max_length=20),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='challenges',
            field=models.TextField(blank=True, help_text='Optional: real challenges faced'),
        ),
        migrations.AddField(
            model_name='project',
            name='features',
            field=models.TextField(blank=True, help_text='One feature per line'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='lessons_learned',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='problem',
            field=models.TextField(blank=True, help_text='What problem does this solve?'),
        ),
        migrations.AddField(
            model_name='project',
            name='role',
            field=models.CharField(blank=True, help_text='e.g. Founder & Full-Stack Developer', max_length=200),
        ),
        migrations.AddField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AddField(
            model_name='project',
            name='solution',
            field=models.TextField(blank=True, help_text='How does the project solve it?'),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(default='Live', help_text='e.g. Live, In Progress', max_length=50),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(help_text='Short summary shown on project cards'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tech_stack',
            field=models.CharField(help_text='Comma-separated, e.g. React, Node.js, MongoDB', max_length=300),
        ),
    ]
