# Generated by Django 6.1.1 on 2026-09-21 22:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_image_project_cover_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, help_text='e.g. Travel Technology, Enterprise Platform', max_length=100),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project_gallery/')),
                ('caption', models.CharField(blank=True, help_text="e.g. 'Admin Dashboard'", max_length=100)),
                ('order', models.PositiveIntegerField(default=0)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='core.project')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
